# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/sartsr/kbot
  # Overrides the image tag whose default is the chart appVersion.
<<<<<<< HEAD
  tag: "V1.0.3-c9b73b5"
=======
  tag: "V1.0.3-757f93f"
>>>>>>> 6e22181 (update version V1.0.3-757f93f)
  os: "linux"
  arch: "arm64"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
