# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: sartsr/kbot.git
  # Overrides the image tag whose default is the chart appVersion.
  tag: "V1.0.3-5da4174"
  arch: "amd64"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
