# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/sartsr/kbot
  # Overrides the image tag whose default is the chart appVersion.
  tag: "V1.0.3-ab0c387"
  os: "linux"
  arch: "arm64"
  version: "V1.0.3"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
